import type { Metadata } from 'next';
import BurgerMenuV2 from '@/app/components/ui/BurgerMenuV2';
import MobileMenu from '@/app/components/ui/MobileMenu';

import {
  Roboto,
  Roboto_Mono,
  Sofia_Sans_Extra_Condensed,
  Anton,
} from 'next/font/google';
import './globals.css';

const robotoSans = Roboto({
  variable: '--font-roboto-sans',
  weight: '500',
  subsets: ['latin'],
  display: 'swap',
});

const robotoMono = Roboto_Mono({
  variable: '--font-roboto-mono',
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

const sofiaSansExtraCondensed = Sofia_Sans_Extra_Condensed({
  variable: '--font-sofia-sans-extra-condensed',
  weight: '600',
  subsets: ['latin'],
  display: 'swap',
});

const anton = Anton({
  variable: '--font-anton',
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoSans.variable} ${robotoMono.variable} ${sofiaSansExtraCondensed.variable} ${anton.variable} antialiased`}
      >
        <BurgerMenuV2 />
        <MobileMenu />

        {children}
      </body>
    </html>
  );
}
